---
- hosts: all
  gather_facts: no
  become : yes

  tasks:

  - name: Update all packages to the latest version
    apt:
      update_cache: yes
      upgrade: dist

  - name: Add source key for nodejs
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present
    register: first_run

  - name: Add source repo for nodejs
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_8.x xenial main"
      state: present
      update_cache: yes    

  - name: install packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - nginx
      - mongodb
      - nodejs
      - python-pip

  - name: install pymongo
    pip:
      name: pymongo
      state: present

  - name: add mongo user
    mongodb_user:
      database: admin
      name: jenkins
      password: 12345
      roles: userAdminAnyDatabase
      state: present
    when: first_run|changed
  
  - name: Restart mongo
    service:
      name: mongodb
      state: restarted
    when: first_run|changed

  - name: configure nginx defaults
    copy:
      src: /var/lib/jenkins/workspace/checkbox/local-conf/default
      dest: /etc/nginx/sites-available/default
      force: yes
      remote_src: True
    when: first_run|changed 

  - name: configure nginx conf
    copy:
      src: /var/lib/jenkins/workspace/checkbox/local-conf/nginx.conf
      dest: /etc/nginx/nginx.conf
      force: yes
      remote_src: True
    when: first_run|changed   

  - name: Restart nginx
    service:
      name: nginx
      state: restarted
    when: first_run|changed

  - name: start node server
    environment: 
      MONGO_PORT: 3002 
      MONGO_IP: localhost 
      MONGO_USER: jenkins 
      MONGO_PASSWORD: 12345
    shell: node server.js
    async: 2592000
    poll: 0
    args:
      chdir: /var/lib/jenkins/workspace/checkbox/server-side/site/