---
- hosts: all
  become: yes
  tasks:

  # Configure build job for checkbox npm application

  - name: get the admin password from vault
    include_vars:
      file: password.yml
      name: vault

  - name: install python-pip
    apt:
      name: python-pip
      state: present
    
  - name: install python-jenkins via pip
    pip: 
      name: python-jenkins 
      state: present

  - name: install python-jenkins via pip
    pip: 
      name: lxml
      state: present

  - name: debug
    debug:
      msg: "{{ vault['admin'] }}"

  - name: add a build job to jenkins
    jenkins_job:
      config: "{{ lookup('file', 'checkbox.xml') }}"
      state: present
      name: checkbox
      url: http://localhost:8080/
      user: admin
      password: "{{ vault['admin'] }}"
      
...
