---
- hosts: all
  become: yes
  tasks:

  # Configure build job for checkbox npm application
  - name: install python-pip
    apt:
      name: python-pip
      state: present
    
  - name: install python-jenkins via pip
    pip: 
      name: python-jenkins 
      state: present

  - name: install python-jenkins via pip
    pip: 
      name: lxml
      state: present

  - name: add a build job to jenkins
    jenkins_job:
      config: "{{ lookup('file', 'checkbox.xml') }}"
      state: present
      name: checkbox
      url: http://localhost:8080/
      user: admin
      password: pass
      
...