---
- hosts: all
  tasks:

    # Configure build job for checkbox npm application
    - jenkins_job:
      config: "{{ lookup('file', 'checkbox.xml') }}"
      name: checkbox
      url: http://localhost:8080
      user: admin
      password: <password>
      
...