---

- hosts: localhost
  gather_facts: no

  tasks:

  - name: Install Packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - build-essential
      - npm
      - nodejs-legacy
      - git
      - curl

  - name: clone iTrust repo
    git:
      repo: ssh://git@github.ncsu.edu/zsthampi/iTrust-v23
      dest: "{{ home }}/development/iTrust-v23"
      accept_hostkey: yes
      force: yes
      update: yes
      version: fuzzer

  - name: Run NPM Install
    command: npm install

  - name: Run Fuzzer
    command: node main.js

  - name: Commit files to Github
    command: "{{ item }}"
    with_items:
      - git add .
      - git commit -m 'Code files have been fuzzed'
      - git push  

