---

- hosts: localhost
  gather_facts: no
  become: yes
  
  vars_prompt:
    - name: 'id'
      prompt: 'github user id'

    - name: 'password'
      prompt: 'password'

  tasks:
  
 #   command: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  
  - name: Install Packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - build-essential
      - npm
      - nodejs
      - git
      - curl
  
  - name: clone iTrust repo
    git:
      repo: ssh://git@github.ncsu.edu/sbnagend/iTrust-v23
      dest: "/home/sbnagend/iTrust-v23"
      accept_hostkey: yes
    become: no
     # force: yes
#      update: yes
#      version: fuzzer

  - name: Run NPM Install
    command: "{{ item }}"
    with_items:
      - npm install
      - node_modules/pegjs/bin/pegjs -o javaparser.js java.pegjs

  - name: Run Fuzzer
    command: node main.js

  - name: Commit files to Github
    command: "{{ item }}"
    with_items:
      - git add .
      - git commit -m 'Code files have been fuzzed'
      - git push  

