---
- hosts: all
  tasks:

  - name: get the admin password from vault
    include_vars:
      file: password.yml
      name: vault

  - name: create development directory
    file:
      path: ./development
      state: directory
      mode: 0755

  - name: install jdk and jre
    apt:
      name: openjdk-8-jre-headless
      state: present
    become: yes

  - name: set JAVA_HOME
    shell: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

  - name: check if tomcat is already installed
    stat:
      path: /home/vagrant/development/apache-tomcat-9.0.0.M26
    register: tomcat

  - name: download tomcat 9
    get_url:
      url: http://www.us.apache.org/dist/tomcat/tomcat-9/v9.0.0.M26/bin/apache-tomcat-9.0.0.M26.tar.gz
      dest: /home/vagrant/development
    when: tomcat.stat.exists == False

  - name: extract tomcat 9
    unarchive:
      src: /home/vagrant/development/apache-tomcat-9.0.0.M26.tar.gz
      dest: /home/vagrant/development/
      remote_src: yes
    when: tomcat.stat.exists == False

  - name: install mysql, workbench, jdbc connectors
    apt:
      name: "{{ item }}"
    become: yes
    become_user: root
    with_items:
      - mysql-server
      - mysql-client
      - libmysql-java
      # - mysql-workbench-community
      # - libmysqlclient18

  - name: install eclipse
    apt:
      name: eclipse
    become: yes
    become_user: root

  - name: change default port on tomcat 9
    replace:
      path: /home/vagrant/development/apache-tomcat-9.0.0.M26/conf/server.xml
      regexp: '<Connector port="8080" protocol="HTTP/1.1"'
      replace: '<Connector port="9090" protocol="HTTP/1.1"'

  - name: start tomcat server
    command: sh /home/vagrant/development/apache-tomcat-9.0.0.M26/bin/startup.sh
    register: start_tomcat
    failed_when: "'Tomcat started' not in start_tomcat.stdout"

  - name: create the SSH public key file
    copy: 
      content: "{{ vault['public_key'] }}"
      dest: /home/vagrant/.ssh/id_rsa.pub
      mode: 0644

  - name: create the SSH private key file
    copy: 
      content: "{{ vault['private_key'] }}"
      dest: /home/vagrant/.ssh/id_rsa
      mode: 0600

  - name: clone iTrust repo
    git:
      repo: ssh://git@github.ncsu.edu/engr-csc326-staff/iTrust-v23.git
      dest: /home/vagrant/iTrust-v23
      accept_hostkey: yes
      force: yes
      update: yes

...