- name: add Github credentials
  vars:
    add_credentials_script: |
      import jenkins.model.*
      import com.cloudbees.plugins.credentials.*
      import com.cloudbees.plugins.credentials.domains.*
      import com.cloudbees.plugins.credentials.impl.*
      store = Jenkins.instance.getExtensionList('com.cloudbees.plugins.credentials.SystemCredentialsProvider')[0].getStore()
      usernameAndPassword = new UsernamePasswordCredentialsImpl(CredentialsScope.GLOBAL,"$id", "$description","$username","$password")
      store.addCredentials(Domain.global(), usernameAndPassword)
  jenkins_script:
    args:
      id: "{{ vault['cred_id'] }}" 
      description: "{{ vault['cred_desc'] }}"
      username: "{{ vault['cred_user'] }}"
      password: "{{ vault['cred_pass'] }}"
    script: "{{ add_credentials_script }}"
    user: "{{ vault['jenkins_user'] }}"
    password: "{{ vault['jenkins_pass'] }}"   

- name: add itrust job
  jenkins_job:
    config: "{{ lookup('file', 'templates/itrust.xml') }}"
    state: present
    name: itrust
    url: http://localhost:8080/
    user: "{{ vault['jenkins_user'] }}"
    password: "{{ vault['jenkins_pass'] }}"
  register: itrust_job_add

- name: trigger itrust build
  vars: 
    start_build_script: |
      import hudson.model.*
      def job = hudson.model.Hudson.instance.getJob("$jobname")
      hudson.model.Hudson.instance.queue.schedule(job, 0)
  jenkins_script:
    args: 
      jobname: itrust
    script: "{{ start_build_script }}"
    user: "{{ vault['jenkins_user'] }}"
    password: "{{ vault['jenkins_pass'] }}"