- hosts: all
  vars: 
    packages:  
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
      - maven
      - gcc
      - git
      - git-core
      - python-dev
      - python-mysqldb
      - libmysqlclient-dev
      - python-setuptools
      - oracle-java8-installer
      - oracle-java8-set-default
      - maven
      - mysql-server
      - python-software-properties

  tasks:
    - name: Add Oracle java apt repository key
      apt_repository:
        repo: 'ppa:webupd8team/java'
      become: yes

    - name: Accept Oracle java license
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
      changed_when: false
      become: yes

    - name: Installing packages
      apt: pkg={{packages}} state=present
      become: yes

    - name: remove case sensitivity in mysql
      blockinfile:
        dest: /etc/mysql/my.cnf
        block: |
          [mysqld]
          lower_case_table_names = 1
      register: mysql_case_sensitivity
      become: yes


    - name: git clone
      command: git clone git@github.ncsu.edu:mpdesai/iTrust-v23.git
      args:
        chdir: /home/meghav
      become: no

   - copy:
        src: /home/mpdesai.xml
        dest: /home/meghav/iTrust-v23/iTrust/WebRoot/META-INF
        owner: mpdesai
        group: mpdesai
        mode: 0664
      become: yes
      become_method: sudo


#    - name: clone iTrust repo
#      git:
#        repo: git@github.ncsu.edu:mpdesai/iTrust-v23.git
#        dest: "/home/meghav"
#        accept_hostkey: yes
#        force: yes
#        update: yes
#        version: master
#      become: yes


    - name: update plugin value on mysql root user
      shell: >
        mysql -u root --execute "UPDATE mysql.user SET plugin = 'mysql_native_password' WHERE user = 'root'; FLUSH PRIVILEGES;"
      become: yes

    - name: Restart mysql
      service:
        name: mysql
        state: restarted
      become: yes
      become_method: sudo

    - name: Enabling mysql to run on boot
      service:
        name: mysql
        state: started
        enabled: true
      become: yes

    - name: restart
      service: name=mysql state=restarted
      become: yes

#    - name: Copying new build to remote
#      synchronize:
#        src: /var/lib/jenkins/workspace/iTrust/iTrust-v23
#        dest: /root/

    - name: installing tomcat
      get_url:
        url: http://mirrors.koehn.com/apache/tomcat/tomcat-8/v8.5.23/bin/apache-tomcat-8.5.23.tar.gz
        dest: /home/meghav
      become: yes

    - name: Unzipping tomcat package
      unarchive:
        src: apache-tomcat-8.5.23.tar.gz
        dest: /home/meghav
        remote_src: True
      become: yes

    - name: Installing jdbc connector
      get_url:
        url: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.44.tar.gz
        dest: /home/meghav
      become: yes

    - name: unzipping jdbc
      command: tar -xvf mysql-connector-java-5.1.44.tar.gz
      args:
        chdir: /home/meghav/
      become: yes


#    - unarchive:
#        src: /home/meghav/mysql-connector-java-5.1.44.tar.gz
#        dest: /root/
#        remote_src: True
#      become: yes

    - name: clean
      command: mvn clean
      args:
        chdir: /home/meghav/iTrust-v23/iTrust/
      become: yes

    - name: compile
      command: mvn compile
      args:
        chdir: /home/meghav/iTrust-v23/iTrust/
      become: yes

    - name: generating war files
      command: mvn package -DskipTests
      args:
        chdir: /home/meghav/iTrust-v23/iTrust/
      become: yes
        
    - name: Rename files for enabling CSS
      shell: cd /home/meghav/iTrust-v23/iTrust/target/; mv iTrust-23.0.0.war iTrust.war
      become: yes

    - name: moving the war files
      copy:
        src: /home/meghav/iTrust-v23/iTrust/target/iTrust.war
        dest: /home/meghav/apache-tomcat-8.5.23/webapps/
        remote_src: True
      become: yes

    - name: start
      shell: cd /home/meghav/apache-tomcat-8.5.23/bin/; ./catalina.sh stop ; ./catalina.sh start
      become: yes

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
      become: yes
